from __future__ import annotations

import re
import textwrap


class ActivationError(ValueError):
    """Raised when default-branch gate activation input is not immutable."""


_CONTROL_PLANE_SHA_RE = re.compile(r"^[0-9a-fA-F]{40}$")
_CHECKOUT_ACTION_SHA = "3d3c42e5aac5ba805825da76410c181273ba90b1"
_SETUP_PYTHON_ACTION_SHA = "5fda3b95a4ea91299a34e894583c3862153e4b97"
_REPOSITORY = "Scorp96/customs-buyer-intelligence-ledger"


def _validated_sha(control_plane_sha: str) -> str:
    if not isinstance(control_plane_sha, str) or not _CONTROL_PLANE_SHA_RE.fullmatch(
        control_plane_sha
    ):
        raise ActivationError("control-plane ref must be an exact 40-hex commit SHA")
    return control_plane_sha.lower()


def _render(template: str, control_plane_sha: str) -> str:
    sha = _validated_sha(control_plane_sha)
    rendered = textwrap.dedent(template).lstrip().replace("@@CONTROL_PLANE_SHA@@", sha)
    if "@@CONTROL_PLANE_SHA@@" in rendered:
        raise ActivationError("control-plane SHA placeholder was not fully rendered")
    return rendered.rstrip() + "\n"


def render_task_gate_workflow(control_plane_sha: str) -> str:
    return _render(
        f"""
        # Generated by scripts/render_astra_gate_workflows.py. Do not hand-edit the pin.
        name: ASTRA task signing gate

        on:
          issues:
            types: [opened, edited, labeled]

        permissions:
          contents: read
          issues: write

        concurrency:
          group: astra-task-sign-${{{{ github.event.issue.number }}}}
          cancel-in-progress: false

        jobs:
          sign:
            if: contains(github.event.issue.labels.*.name, 'astra-task/proposed')
            runs-on: ubuntu-latest
            timeout-minutes: 5
            steps:
              - name: Checkout immutable reviewed ASTRA control plane
                uses: actions/checkout@{_CHECKOUT_ACTION_SHA}
                with:
                  repository: {_REPOSITORY}
                  ref: @@CONTROL_PLANE_SHA@@
                  persist-credentials: false

              - name: Set up Python
                uses: actions/setup-python@{_SETUP_PYTHON_ACTION_SHA}
                with:
                  python-version: '3.11'

              - name: Sign eligible ASTRA task
                run: python scripts/astra_task_gate.py --event "$GITHUB_EVENT_PATH"
                env:
                  GITHUB_TOKEN: ${{{{ github.token }}}}
                  ASTRA_TASK_HMAC_KEY_B64: ${{{{ secrets.ASTRA_TASK_HMAC_KEY_B64 }}}}
                  ASTRA_ALLOWED_PROPOSERS: Scorp96
                  ASTRA_WORKER_ID: scorp-windows-01
                  ASTRA_REPOSITORY_ID: cbi-primary
                  ASTRA_ALLOWED_BASE_REFS_EXACT: cbi-v6-3-demand-expansion
                  ASTRA_ALLOWED_BASE_REF_PREFIXES: astra-
                  ASTRA_MAX_TASK_AGE_SECONDS: '1800'
        """,
        control_plane_sha,
    )


def render_receipt_gate_workflow(control_plane_sha: str) -> str:
    return _render(
        f"""
        # Generated by scripts/render_astra_gate_workflows.py. Do not hand-edit the pin.
        name: ASTRA receipt verification gate

        on:
          issue_comment:
            types: [created]

        permissions:
          contents: read
          issues: write

        concurrency:
          group: astra-receipt-verify-${{{{ github.event.issue.number }}}}
          cancel-in-progress: false

        jobs:
          verify:
            if: startsWith(github.event.comment.body, 'ASTRA_RECEIPT_V1 ')
            runs-on: ubuntu-latest
            timeout-minutes: 5
            steps:
              - name: Checkout immutable reviewed ASTRA control plane
                uses: actions/checkout@{_CHECKOUT_ACTION_SHA}
                with:
                  repository: {_REPOSITORY}
                  ref: @@CONTROL_PLANE_SHA@@
                  persist-credentials: false

              - name: Set up Python
                uses: actions/setup-python@{_SETUP_PYTHON_ACTION_SHA}
                with:
                  python-version: '3.11'

              - name: Verify ASTRA worker receipt
                run: python scripts/astra_receipt_gate.py --event "$GITHUB_EVENT_PATH"
                env:
                  GITHUB_TOKEN: ${{{{ github.token }}}}
                  ASTRA_TASK_HMAC_KEY_B64: ${{{{ secrets.ASTRA_TASK_HMAC_KEY_B64 }}}}
                  ASTRA_RECEIPT_HMAC_KEY_B64: ${{{{ secrets.ASTRA_RECEIPT_HMAC_KEY_B64 }}}}
        """,
        control_plane_sha,
    )
